language: node_js
sudo: true
node_js:
- stable
script:
- npm test
env:
  global:
  - CF_APP=dialog-tool
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=WatsonPlatformServices
  - CF_SPACE=demos
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: $CF_USERNAME
  password: $CF_PASSWORD
  organization: WatsonPlatformServices
  space: demos
  on:
    repo: watson-developer-cloud/dialog-tool
    branch: master
  skip_cleanup: true
notifications:
  email: false